version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  hashy-parmentier.cyrhades.fr:
    image: anssi/fcsc2021-crypto-hashy-parmentier:latest
    ports:
      - ${PORT_SSH}:4000
